[package]
name = "snnsim"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.1"
cudarc = { version = "0.16.4", features = ["cuda-version-from-build-system"] }

[dev-dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.1"
indicatif = "0.17.11"